// For admin layout
export { default as Sidebar } from './Admin/Sidebar'
export { default as HeaderComponent } from './Admin/HeaderComponent'
export { default as TableManagement } from './Admin/TableManagement'
export { default as UploadImage } from './Admin/UploadImage'
export { default as BicycleManageAction } from './Admin/BicycleManageAction'
export { default as AddBicycleModal } from './Admin/AddBicycleModal'
export { default as EditBicycleModal } from './Admin/EditBicycleModal'

// Other other layouts
export { default as BicycleCard } from './BicycleCard'
export { default as ImgCarousel } from './ImgCarousel'
export { default as HomeNavigation } from './HomeNavigation'
export { default as Logo } from './Logo'
export { default as NavLink } from './NavLink'
export { default as Table } from './Table'
export { default as Select } from './Select'
export { default as HomeFooter } from './HomeFooter'
export { default as SearchInput } from './SearchInput'
export { default as LoadingAnimation } from './LoadingAnimation'
export { default as Pagination } from './Pagination'
export { default as LanguageSelect } from './LanguageSelect'
export { default as EmptyData } from './EmptyData'
export { default as OrderDetailModal } from './Admin/OrderDetailModal'
